import type { PatientRequest } from "./types";

export const _mockRequests: PatientRequest[] = [
  {
    date: "2025-04-04T00:00:00.000Z",
    done: false,
    employeeResponsibleId: null,
    id: "createAccount111",
    idCardPhoto: "/images/Obcanka_Light.webp",
    idCardPhotoBack: "/images/Obcanka_Light.webp",
    patientId: "cm1ta3xyf0i0qmlcjevauxjhv",
    requestType: "profileActivation",
  },
  {
    birthCertificatePhoto: "/images/Birth_Certificate.svg",
    childInsuranceNumber: "2355041271",
    date: "2025-04-01T00:00:00.000Z",
    done: false,
    employeeResponsibleId: null,
    id: "addProfile2222",
    patientId: "cm1taj9lveiyxmlcjwp4b56ch",
    requestType: "addDependentProfile",
  },
  {
    date: "2025-04-05T00:00:00.000Z",
    done: false,
    employeeResponsibleId: null,
    id: "createAccount111",
    idCardPhoto: "/images/Obcanka_Vzor.jpg",
    idCardPhotoBack: "/images/Obcanka_Vzor_Zezadu.jpg",
    patientId: "cm1taj9lveiyxmlcjwp4b56ch",
    requestType: "profileActivation",
  },
  {
    birthCertificatePhoto: "/images/Birth_Certificate.svg",
    childInsuranceNumber: "111111111",
    date: "2025-04-01T00:00:00.000Z",
    done: false,
    employeeResponsibleId: "test-id",
    id: "addProfile2222",
    patientId: "cm1taj9lveiyxmlcjwp4b56ch",
    requestType: "addDependentProfile",
  },
  {
    date: "2025-04-07T00:00:00.000Z",
    done: false,
    employeeResponsibleId: null,
    id: "newAppointment333",
    patientId: "cm1tab0lc6z74mlcjw8chggyy",
    preferredTime: "AFTERNOON",
    refferal: false,
    requestType: "appointmentAssign",
    selectedFacilityId: "Hor12",
    selectedFamilyMembers: [],
    selectedServiceId: "DetskaAlergologieAPneumologie",
  },
  {
    date: "2025-03-28T00:00:00.000Z",
    done: false,
    employeeResponsibleId: "test-id",
    id: "addProfile2222",
    insurancecompanyNumber: "111",
    patientId: "cm1taj9lveiyxmlcjwp4b56ch",
    profileId: "J3",
    requestType: "profileDataChange",
  },
];
