export const palliativeCareThemes = {
  balanceSheet: "Multiprofesní rozvaha",
  bereavementCare: "Péče o pozůstalé",
  careLimitation: "Limitace péče, dříve vyslovené",
  careTargets: "Formulace cíle a plánu péče",
  communicationSupport: "Podpora při obtížné komunikaci včetně emocí a konfliktů",
  decisionMechanism: "Stanovení rozhodovacího mechanizmu",
  expectations: "Formulace porozumění a očekávání",
  familyConference: "Rodinná konference",
  outsideCareCoordination: "Koordinace péče mimo poskytovatele",
  perinatalCare: "Perinatální péče",
  phoneConsultation: "Telefonická konzultace",
  psychologicalSupportCaregiver: "Pečující - psychologická podpora včetně krizové intervence",
  psychologicalSupportPatient: "Pacient - psychologická podpora včetně krizové intervence",
  socialFinanceSupport: "Sociální a finanční podpora",
  spiritual: "Spirituální intervence, naděje, smysl, religiozita",
  symptoms: "Symptomová intervence",
  terminalCarePatient: "Péče o pacienta v terminálním stádiu",
};
